language: php
php:
  - 5.3
before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar self-update
  - php composer.phar install --dev
  - mkdir tests/Simope/storage
  - chmod 777 tests/Simope/storage
  
script: phpunit --configuration phpunit.xml.dist
